### ISSUE TITLE
Missing filenames

### ISSUE THREAD

**Issue by cvanderaa** [theislab/singlecell_proteomics#1]
Dear Sabrina, @SabrinaRichter 

Thank you for the the reproduction script! I am trying to reproduce your analysis, but can't figure out which input files you used for the TSCP analysis. In the `Data Loading` section, you set twice `filename = '...'`. I must admit I'm a python novice, but this looks like a placeholder rather that pointing to an actual file. Could you please tell which files you used as input. I found several files in the `DIANN1.8_SingleCells_CellCycle.zip` folder from the repo mentioned in the Brunner et al. 2022 paper: https://www.ebi.ac.uk/pride/archive/projects/PXD024043

Thanks in advance, 
Chris

**Comment by SabrinaRichter** [comment]
Dear Chris,

Thanks for catching this! We adjusted the PRIDE upload, you can find the used files here https://www.ebi.ac.uk/pride/archive/projects/PXD024043 in DIANN1.8_SingleCells_CellCycle.7z.

I also added two more files to this repo so that it is actually possible to run the notebook instead of just functioning as a documentation.

Best,
Sabrina

**Comment by cvanderaa** [comment]
Thank you for taking the effort of adapting the repo and making sure the notebook can be run. 

Quick question: where `20210919_DIANN_SingleCellOutput.pg_matrix_notnormalized.tsv` and `0210919_DIANN_SingleCellOutput.pg_matrix_cellcyclepred.tsv` generated by DIA-NN? If not, how where they generated?

**Comment by AndreasDavidBrunner** [comment]
Hi cvanderaa,

We analysed all data with Spectronaut and DIA-NN since reviewers asked for this comparison. 

All data are deposited in the PRIDE repository as presented in the methods section of the paper. 
The data analysed and presented in the main paper are DIA-NN data using a hybrid library created by MSFRAGGER. All processing steps are described in depth in the methods section of the paper. 

If there are any other questions left with regards to the paper, I can offer quick replies by E-Mail via abrunner@biochem.mpg.de . 

Cheers
Andreas-David Brunner
